env:
  global:
    secure: Oa7ylDng0dExi+AcWfksNJSEM07wQqWtEhx783ZX47tgQcNaE7m5ba1DqVm2jEQHYchxBaUbPMP9631Hihtz3FhDrwb4WKwlLS4RtisD0LRsajIuqZPmYgtyoU1UpbbxZd8I1hrsbUTO8zRxJLnwxQ6hbd+ZFW/JYmw6EWtrxFvMDDnUikNxw+dik7QGVqWBV3TFvQOu0y6VQR6uLaXFWuLUbLxgG8yqisdecvTlpGSw/oDH07HZL65xhRAWmORC7dkDC+ESEWC+NYRWCubNkRv/kuVzmkbGa0FXieHZLrVT5PS0MeYhpw2+lwkNkU2QhJXiUNWZ+IopusaSEm1djklZwwOdMg0dOsAeyDFbqAVcwAFwfqJEMHtzbkbS1JBue5snEswqo9yGa8lw7BrGTP437YnUXM/sXCv9UmT0rg6TGZkSlFn6TNvDOsTh74RnP2WvSYCGS5j9MwgqxlnpgGYHZ4cv9MlAdZNh/EfFVjK82lVNVn8rUm4BX/aUHJo8bgCtx9NS0EUdV4Ntk3kjJew+gnDny0cqfYpHf3dpg3JHV3TNDWosYbOcpTFkCzLwjid5mdgL5NGu5mrLPgIOC9dze2FLYkMILtmMym+ySBxLPg3OS6cKArCwsTAnp6buRqX/xtTjK7c8Aw4RegUWmCcf4qw9halSacMQteiWmH0=
script:
- echo "hello world"
- docker build --target development --tag todo-app:dev .
- docker build --target production --tag todo-app:prod .
- docker build --target test --tag todo-app:test .
- docker run todo-app:test tests/test_viewmodel.py
- docker run todo-app:test tests/test_trello_api_calls.py
- docker run --env-file .env.test todo-app:test tests/test_app.py
