script:
- echo "hello world"
- docker build --target development --tag todo-app:dev .
- docker build --target production --tag todo-app:prod .
- docker build --target test --tag todo-app:test .
- docker run todo-app:test tests/test_viewmodel.py
- docker run --env-file .env todo-app:test tests/test_trello_api_calls.py
- docker run --env-file .env.test todo-app:test tests/test_app.py